// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:7c2c965a-7efa-4ae4-901a-274eebe73cf3",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_GyR0cMxyT",
    "aws_user_pools_web_client_id": "7k2qs1ji91afmmkbpfk5lctctu",
    "oauth": {}
};


export default awsmobile;
