// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-2:2617b03f-5816-4fae-8d05-fb5f00dbdb72',
    'aws_cognito_region': 'us-east-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'ellergicawsmobile-hosting-mobilehub-1153337746',
    'aws_content_delivery_bucket_region': 'us-east-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1sm1wdj0etg9g.cloudfront.net',
    'aws_mobile_analytics_app_id': '691cc21a16d2487b917458cf797988f9',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '54e9b968-c449-4611-8f07-7bc317593afb',
    'aws_project_name': 'E-llergic-AWSmobile',
    'aws_project_region': 'us-east-2',
    'aws_resource_name_prefix': 'ellergicawsmobile-mobilehub-1153337746',
}

export default awsmobile;
